package com.appsdeveloperblog.estore.OrdersService.core.events;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.appsdeveloperblog.estore.OrdersService.core.model.OrderStatus;

import lombok.Value;

@DynamoDBTable(tableName = "orders")
@Value
public class OrderApprovedEvent {

	@DynamoDBHashKey(attributeName = "orderId")
	@DynamoDBAutoGeneratedKey
	private final String orderId;
	
	@DynamoDBAttribute
	private final OrderStatus orderStatus = OrderStatus.APPROVED;
}
