/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.appsdeveloperblog.estore.OrdersService.core.events;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.appsdeveloperblog.estore.OrdersService.core.model.OrderStatus;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "orders")
public class OrderCreatedEvent {
	
	@DynamoDBHashKey(attributeName = "orderId")
	@DynamoDBAutoGeneratedKey
    private String orderId;
	
	@DynamoDBAttribute
    private String productId;
    
	@DynamoDBAttribute
    private String userId;
    
	@DynamoDBAttribute
    private int quantity;
    
	@DynamoDBAttribute
    private String addressId; 
    
	@DynamoDBAttribute
    private OrderStatus orderStatus;
}
