package com.appsdeveloperblog.estore.OrdersService.core.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Value;

@Value
@DynamoDBTable(tableName="orders")
public class OrderSummary {
	
	@DynamoDBHashKey(attributeName = "orderId")
	@DynamoDBAutoGeneratedKey
	private final String orderId;
	
	@DynamoDBAttribute
	private final OrderStatus orderStatus;
	
	@DynamoDBAttribute
	private final String message;

}
