package com.appsdeveloperblog.estore.OrdersService.command.rest;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "products")
public class OrderCreateRest {
	
    @DynamoDBHashKey(attributeName = "productId")
	@DynamoDBAutoGeneratedKey
    @NotBlank(message = "Order productId is a required field")
    private String productId;
    
    @DynamoDBAttribute
    @Min(value = 1, message = "Quantity cannot be lower than 1")
    @Max(value = 5, message = "Quantity cannot be larger than 5")
    private int quantity;
    
    @DynamoDBAttribute
    @NotBlank(message = "Order addressId is a required field")
    private String addressId;
    
}
