package com.appsdeveloperblog.estore.ProductsService.core.data;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Entity
@Data
@DynamoDBTable(tableName = "products")
public class ProductEntity implements Serializable {
	private static final long serialVersionUID = -227264951080660124L;

	@Id
	@Column(unique=true)
	@DynamoDBHashKey(attributeName = "productId")
	@DynamoDBAutoGeneratedKey
	private String productId;
	
	@DynamoDBAttribute
	@Column(unique=true)
	private String title;
	
	@DynamoDBAttribute
	private BigDecimal price;
	
	@DynamoDBAttribute
	private Integer quantity;
}
