package com.appsdeveloperblog.estore.ProductsService.command;

import java.math.BigDecimal;

import org.axonframework.modelling.command.TargetAggregateIdentifier;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Builder;
import lombok.Data;

@Builder
@Data
@DynamoDBTable(tableName="products")
public class CreateProductCommand {
	
	@DynamoDBHashKey(attributeName = "productId")
	@DynamoDBAutoGeneratedKey
	@TargetAggregateIdentifier
	private final String productId;
	
	@DynamoDBAttribute
	private final String title;
	
	@DynamoDBAttribute
	private final BigDecimal price;
	
	@DynamoDBAttribute
	private final Integer quantity;
	
}
