package com.appsdeveloperblog.estore.OrdersService.command.commands;



import org.axonframework.modelling.command.TargetAggregateIdentifier;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
@DynamoDBTable(tableName = "orders")
public class ApproveOrderCommand {
	
	@DynamoDBHashKey(attributeName = "orderId")
	@DynamoDBAutoGeneratedKey
	@TargetAggregateIdentifier
	private final String orderId;
}
