/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.appsdeveloperblog.estore.OrdersService.command.commands;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.appsdeveloperblog.estore.OrdersService.core.model.OrderStatus;
import lombok.Builder;
import lombok.Data;
import org.axonframework.modelling.command.TargetAggregateIdentifier;

@Builder
@Data
@DynamoDBTable(tableName = "orders")
public class CreateOrderCommand {
      
	@DynamoDBHashKey(attributeName = "orderId")
	@DynamoDBAutoGeneratedKey
    @TargetAggregateIdentifier
    public final String orderId;
    
	@DynamoDBAttribute
    private final String userId;
	
	@DynamoDBAttribute
    private final String productId;
	
	@DynamoDBAttribute
    private final int quantity;
	
	@DynamoDBAttribute
    private final String addressId; 
	
	@DynamoDBAttribute
    private final OrderStatus orderStatus;
}
