package com.appsdeveloperblog.estore.OrdersService.command.commands;

import org.axonframework.modelling.command.TargetAggregateIdentifier;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Value;

@Value
@DynamoDBTable(tableName = "orders")
public class RejectOrderCommand {

	@DynamoDBHashKey(attributeName = "orderId")
	@DynamoDBAutoGeneratedKey
	@TargetAggregateIdentifier
	private final String orderId;
	
	@DynamoDBAttribute
	private final String reason;
}
